repos:
  - repo: local
    hooks:
      - id: whitespace
        name: strip whitespace
        entry: find tinygrad -type f -name "*.py" -exec sed -i '' 's/ *$//' '{}' ';'
        language: system
        always_run: true
        pass_filenames: false
      - id: ruff
        name: ruff
        entry: ruff check .
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy tinygrad/ --strict-equality
        language: system
        always_run: true
        pass_filenames: false
      - id: docs2
        name: docs2
        entry: python3 docs/abstractions2.py
        language: system
        always_run: true
        pass_filenames: false
      - id: devicetests
        name: select GPU tests
        entry: env GPU=1 PYTHONPATH="." pytest test/test_uops.py test/test_custom_function.py test/test_search.py
        language: system
        always_run: true
        pass_filenames: false
      - id: tests
        name: subset of tests
        entry: env PYTHONPATH="." python3 -m pytest -n=4 test/unit/ test/test_ops.py test/test_dtype.py test/test_schedule.py test/test_custom_function.py test/test_assign.py test/test_symbolic_shapetracker.py
        language: system
        always_run: true
        pass_filenames: false
      - id: example
        name: multi device tests
        entry: python3 test/external/external_test_example.py
        language: system
        always_run: true
        pass_filenames: false
      - id: pylint
        name: pylint
        entry: env PYTHONPATH="." python3 -m pylint tinygrad/
        language: system
        always_run: true
        pass_filenames: false